---

  - name: Create group {{ user_group_name }} with custom GID {{ user_group_gid }}
    group:
      name: "{{ user_group_name }}"
      state: present
      gid: "{{ user_group_gid }}"
    when: user_group_gid != ""

  - name: Create group {{ user_group_name }}
    group:
      name: "{{ user_group_name }}"
      state: present
    when: user_group_gid == ""

  - name: Create {{ user_name }} user with custom UID {{ user_uid }}
    user:
      name: "{{ user_name }}"
      shell: "{{ user_shell }}"
      group: "{{ user_group_primary }}"
      groups: "{{ user_group_list }}"
      system: yes
      home: "{{ user_home }}"
      generate_ssh_key: yes
      uid: "{{ user_uid }}"
    when: user_uid != ""

  - name: Create {{ user_name }} user
    user:
      name: "{{ user_name }}"
      shell: "{{ user_shell }}"
      group: "{{ user_group_primary }}"
      groups: "{{ user_group_list }}"
      system: yes
      home: "{{ user_home }}"
      generate_ssh_key: yes
    when: user_uid == ""

  - name: Ensure home directory {{ user_home }} is owned by {{ user_name }} user
    file:
      state: directory
      path: "{{ user_home }}"
      owner: "{{ user_name }}"
      group: "{{ user_group_name }}"
      mode: 0755

  - name: Adds SSH authorized keys to {{ user_name }}
    authorized_key:
      user: "{{ user_name }}"
      key: "{{ user_authorized_keys }}"

  - name: Give {{ user_name }} user sudo
    template:
      src: sudoers.tpl
      dest: "/etc/sudoers.d/{{ user_name }}"
      owner: root
      group: root
      mode: 0440
      validate: visudo -cf %s
    when: user_sudo

  - name: Create {{ user_name }}'s config folder (if it's `aegir`)
    file:
      state: directory
      path: "{{ user_home }}/config"
      owner: "{{ user_name }}"
      group: "{{ user_group_name }}"
      mode: 0711
    when: user_name == "aegir"
