---

  - name: Create group {{ user_group_name }} with custom GID
    group:
      name: "{{ user_group_name }}"
      state: present
      gid: "{{ user_group_gid }}"
    when: user_group_gid

  - name: Create group {{ user_group_name }}
    group:
      name: "{{ user_group_name }}"
      state: present
    when: not user_group_gid

  - name: Create {{ user_name }} user with custom UID
    user:
      name: "{{ user_name }}"
      shell: "{{ user_shell }}"
      groups: "{{ user_group_list }}"
      system: yes
      home: "{{ user_home }}"
      generate_ssh_key: yes
      uid: "{{ user_uid }}"
    when: user_uid

  - name: Create {{ user_name }} user
    user:
      name: "{{ user_name }}"
      shell: "{{ user_shell }}"
      groups: "{{ user_group_list }}"
      system: yes
      home: "{{ user_home }}"
      generate_ssh_key: yes
    when: not user_uid

  - name: Ensure home directory {{ user_home }} is owned by {{ user_name }} user
    file:
      state: directory
      path: "{{ user_home }}"
      owner: "{{ user_name }}"
      group: "{{ user_group_name }}"
      mode: 0755

  - name: Create {{ user_name }}'s authorized keys file
    copy:
      dest: "{{ user_home }}/.ssh/authorized_keys"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      content: "{{ user_authorized_keys }}"
      mode: 0644

  - name: Give {{ user_name }} user sudo
    template:
      src: sudoers.tpl
      dest: "/etc/sudoers.d/{{ user_name }}"
      owner: root
      group: root
      mode: 0440
      validate: visudo -cf %s
    when: user_sudo

  - name: Create {{ user_name }}'s config folder (if it's `aegir`)
    file:
      state: directory
      path: "{{ user_home }}/config"
      owner: "{{ user_name }}"
      group: "{{ user_group_name }}"
      mode: 0755
    when: user_name=="aegir"
